### ISSUE TITLE
Atualizar para Java 11

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [alesaudate/rest#1]

**Comment by alesaudate** [comment]
Apoiado! :) 

Mas o livro precisa seguir a mesma linha. Senão não ficam condizentes. Além disso, tenho a intenção de fazer a atualização do livro para algo mais estrutural. Tirar um tanto de teoria e substituir por práticas mais modernas. Além disso, abandonar JAX-RS e partir para o modelo Spring Boot.

**Comment by luisangelorjr** [comment]
SpringBoot <3

**Comment by alesaudate** [comment]
Tá no forno ;)
